apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-family-azure
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  # Use the version that keeps appearing
  package: xpkg.upbound.io/upbound/provider-family-azure:v2.3.0