apiVersion: network.azure.upbound.io/v1beta2
kind: VirtualNetwork
metadata:
  name: aks-vnet
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  forProvider:
    addressSpace:
      - 10.0.0.0/16
    location: EastUS
    resourceGroupNameRef:
      name: my-crossplane-rg
  providerConfigRef:
    name: default
---
apiVersion: network.azure.upbound.io/v1beta2
kind: Subnet
metadata:
  name: aks-subnet
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  forProvider:
    addressPrefixes:
      - 10.0.1.0/24
    resourceGroupNameRef:
      name: my-crossplane-rg
    virtualNetworkNameRef:
      name: aks-vnet
  providerConfigRef:
    name: default
---
apiVersion: containerservice.azure.upbound.io/v1beta2
kind: KubernetesCluster
metadata:
  name: my-aks-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  forProvider:
    location: EastUS
    resourceGroupNameRef:
      name: my-crossplane-rg
    dnsPrefix: my-aks-controlplane
    defaultNodePool:
      name: default
      nodeCount: 1
      vmSize: Standard_DC2s_v3
      vnetSubnetId: /subscriptions/9d4d069d-d03a-4639-9b34-fa963ddadd3b/resourceGroups/my-crossplane-rg/providers/Microsoft.Network/virtualNetworks/aks-vnet/subnets/aks-subnet
    identity:
      type: SystemAssigned
    networkProfile:
      networkPlugin: azure
      loadBalancerSku: standard
      serviceCidr: 10.2.0.0/16   # avoid overlap with 10.0.0.0/16 VNet
      dnsServiceIp: 10.2.0.10
      dockerBridgeCidr: 172.17.0.1/16
  providerConfigRef:
    name: default