apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: wordpress
type: Opaque
stringData:
  mariadb-root-password: "JnrKoKo2012@"
  mariadb-password: "JnrKoKo2012@"
  wordpress-password: "JnrKoKo2012@"
